// ─── Seller Management Demo Data ───────────────────────────────────────────
export const sellerDemoData = [
  {
    _id: "SEL-12001",
    name: "Anika Rahman",
    phone: "08+ 123 456 789",
    email: "anika.rahman@gmail.com",
    location: "Dhaka, Bangladesh",
    avatar: "https://i.pravatar.cc/150?img=47",
    document: "nid_anika.pdf",
    joinDate: "2024-01-15",
    totalProducts: 34,
    totalSales: 4200,
    status: "Active",
  },
  {
    _id: "SEL-12002",
    name: "Sara Khan",
    phone: "08+ 987 654 321",
    email: "sara.khan@outlook.com",
    location: "Kent, Utah",
    avatar: "https://i.pravatar.cc/150?img=48",
    document: "nid_sara.pdf",
    joinDate: "2024-02-20",
    totalProducts: 22,
    totalSales: 2900,
    status: "Active",
  },
  {
    _id: "SEL-12003",
    name: "Mina Patel",
    phone: "08+ 111 222 333",
    email: "mina.patel@yahoo.com",
    location: "Austin, Texas",
    avatar: "https://i.pravatar.cc/150?img=49",
    document: "nid_mina.pdf",
    joinDate: "2024-03-10",
    totalProducts: 18,
    totalSales: 1750,
    status: "Inactive",
  },
  {
    _id: "SEL-12004",
    name: "Priya Sharma",
    phone: "08+ 444 555 666",
    email: "priya.sharma@gmail.com",
    location: "Mumbai, India",
    avatar: "https://i.pravatar.cc/150?img=50",
    document: "nid_priya.pdf",
    joinDate: "2024-04-05",
    totalProducts: 51,
    totalSales: 8100,
    status: "Active",
  },
  {
    _id: "SEL-12005",
    name: "Lena Müller",
    phone: "08+ 777 888 999",
    email: "lena.muller@web.de",
    location: "Berlin, Germany",
    avatar: "https://i.pravatar.cc/150?img=51",
    document: "nid_lena.pdf",
    joinDate: "2024-05-18",
    totalProducts: 9,
    totalSales: 640,
    status: "Pending",
  },
  {
    _id: "SEL-12006",
    name: "Yuki Tanaka",
    phone: "08+ 321 654 987",
    email: "yuki.tanaka@mail.jp",
    location: "Tokyo, Japan",
    avatar: "https://i.pravatar.cc/150?img=52",
    document: "nid_yuki.pdf",
    joinDate: "2024-06-22",
    totalProducts: 27,
    totalSales: 3300,
    status: "Active",
  },
  {
    _id: "SEL-12007",
    name: "Fatima Al-Hassan",
    phone: "08+ 100 200 300",
    email: "fatima.alhassan@gmail.com",
    location: "Cairo, Egypt",
    avatar: "https://i.pravatar.cc/150?img=53",
    document: "nid_fatima.pdf",
    joinDate: "2024-07-14",
    totalProducts: 15,
    totalSales: 1100,
    status: "Active",
  },
  {
    _id: "SEL-12008",
    name: "Chloe Martin",
    phone: "08+ 600 700 800",
    email: "chloe.martin@orange.fr",
    location: "Paris, France",
    avatar: "https://i.pravatar.cc/150?img=54",
    document: "nid_chloe.pdf",
    joinDate: "2024-08-01",
    totalProducts: 41,
    totalSales: 5600,
    status: "Inactive",
  },
];

// ─── User Management Demo Data ──────────────────────────────────────────────
export const userDemoData = [
  {
    _id: "USR-20001",
    name: "John Doe",
    phone: "08+ 123 456 789",
    email: "john.doe@gmail.com",
    location: "Kent, Utah",
    avatar: "https://i.pravatar.cc/150?img=32",
    joinDate: "2024-01-10",
    totalOrders: 12,
    totalSpent: 890,
    status: "Active",
  },
  {
    _id: "USR-20002",
    name: "Emily Clark",
    phone: "08+ 222 333 444",
    email: "emily.clark@yahoo.com",
    location: "Seattle, WA",
    avatar: "https://i.pravatar.cc/150?img=33",
    joinDate: "2024-02-14",
    totalOrders: 5,
    totalSpent: 340,
    status: "Active",
  },
  {
    _id: "USR-20003",
    name: "Carlos Rivera",
    phone: "08+ 555 666 777",
    email: "carlos.rivera@hotmail.com",
    location: "Miami, FL",
    avatar: "https://i.pravatar.cc/150?img=34",
    joinDate: "2024-03-22",
    totalOrders: 20,
    totalSpent: 1450,
    status: "Inactive",
  },
  {
    _id: "USR-20004",
    name: "Hannah Lee",
    phone: "08+ 888 999 000",
    email: "hannah.lee@gmail.com",
    location: "San Francisco, CA",
    avatar: "https://i.pravatar.cc/150?img=35",
    joinDate: "2024-04-18",
    totalOrders: 8,
    totalSpent: 620,
    status: "Active",
  },
  {
    _id: "USR-20005",
    name: "Omar Faruk",
    phone: "08+ 111 333 555",
    email: "omar.faruk@gmail.com",
    location: "Chittagong, BD",
    avatar: "https://i.pravatar.cc/150?img=36",
    joinDate: "2024-05-05",
    totalOrders: 3,
    totalSpent: 210,
    status: "Active",
  },
  {
    _id: "USR-20006",
    name: "Sophia Brown",
    phone: "08+ 222 444 666",
    email: "sophia.brown@outlook.com",
    location: "London, UK",
    avatar: "https://i.pravatar.cc/150?img=37",
    joinDate: "2024-06-12",
    totalOrders: 15,
    totalSpent: 1200,
    status: "Inactive",
  },
  {
    _id: "USR-20007",
    name: "Raj Patel",
    phone: "08+ 333 555 777",
    email: "raj.patel@rediffmail.com",
    location: "Ahmedabad, India",
    avatar: "https://i.pravatar.cc/150?img=38",
    joinDate: "2024-07-08",
    totalOrders: 7,
    totalSpent: 480,
    status: "Active",
  },
  {
    _id: "USR-20008",
    name: "Nina Schmidt",
    phone: "08+ 444 666 888",
    email: "nina.schmidt@gmx.de",
    location: "Hamburg, Germany",
    avatar: "https://i.pravatar.cc/150?img=39",
    joinDate: "2024-08-20",
    totalOrders: 11,
    totalSpent: 930,
    status: "Active",
  },
  {
    _id: "USR-20009",
    name: "Lucia Ferrari",
    phone: "08+ 777 888 111",
    email: "lucia.ferrari@libero.it",
    location: "Rome, Italy",
    avatar: "https://i.pravatar.cc/150?img=40",
    joinDate: "2024-09-03",
    totalOrders: 2,
    totalSpent: 95,
    status: "Active",
  },
  {
    _id: "USR-20010",
    name: "James Wilson",
    phone: "08+ 999 111 222",
    email: "james.wilson@icloud.com",
    location: "Chicago, IL",
    avatar: "https://i.pravatar.cc/150?img=41",
    joinDate: "2024-10-17",
    totalOrders: 18,
    totalSpent: 1780,
    status: "Inactive",
  },
];

// ─── Product Management Demo Data ───────────────────────────────────────────
export const productDemoData = [
  {
    _id: "PRD-30001",
    name: "Polo T-Shirt Red",
    sellerName: "Anika Fashion",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana_na_folha_%28cropped%29.jpg/240px-Banana_na_folha_%28cropped%29.jpg",
    category: "T-Shirts",
    price: 15,
    stock: 120,
    status: "Pending",
    description:
      "Premium quality polo t-shirt made from 100% cotton. Available in multiple sizes.",
  },
  {
    _id: "PRD-30002",
    name: "Slim Fit Jeans",
    sellerName: "Sara Khan",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana_na_folha_%28cropped%29.jpg/240px-Banana_na_folha_%28cropped%29.jpg",
    category: "Pants",
    price: 45,
    stock: 80,
    status: "Pending",
    description:
      "Slim fit denim jeans with stretch fabric for maximum comfort.",
  },
  {
    _id: "PRD-30003",
    name: "Floral Summer Dress",
    sellerName: "Mina Patel",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana_na_folha_%28cropped%29.jpg/240px-Banana_na_folha_%28cropped%29.jpg",
    category: "Dresses",
    price: 32,
    stock: 55,
    status: "Pending",
    description:
      "Light and breezy floral print dress perfect for summer outings.",
  },
  {
    _id: "PRD-30004",
    name: "Leather Jacket",
    sellerName: "Priya Sharma",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana_na_folha_%28cropped%29.jpg/240px-Banana_na_folha_%28cropped%29.jpg",
    category: "Jackets",
    price: 120,
    stock: 30,
    status: "Pending",
    description:
      "Genuine leather jacket with zipper pockets and quilted lining.",
  },
  {
    _id: "PRD-30005",
    name: "Running Sneakers",
    sellerName: "Lena Müller",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana_na_folha_%28cropped%29.jpg/240px-Banana_na_folha_%28cropped%29.jpg",
    category: "Footwear",
    price: 78,
    stock: 200,
    status: "Pending",
    description:
      "Lightweight running sneakers with memory foam insole and mesh upper.",
  },
  {
    _id: "PRD-30006",
    name: "Woolen Scarf",
    sellerName: "Yuki Tanaka",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana_na_folha_%28cropped%29.jpg/240px-Banana_na_folha_%28cropped%29.jpg",
    category: "Accessories",
    price: 18,
    stock: 300,
    status: "Pending",
    description: "Soft merino wool scarf in classic plaid pattern.",
  },
  {
    _id: "PRD-30007",
    name: "Graphic Hoodie",
    sellerName: "Fatima Al-Hassan",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana_na_folha_%28cropped%29.jpg/240px-Banana_na_folha_%28cropped%29.jpg",
    category: "Hoodies",
    price: 55,
    stock: 95,
    status: "Pending",
    description:
      "Cozy fleece-lined hoodie with unique graphic print on the back.",
  },
  {
    _id: "PRD-30008",
    name: "Formal Blazer",
    sellerName: "Chloe Martin",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana_na_folha_%28cropped%29.jpg/240px-Banana_na_folha_%28cropped%29.jpg",
    category: "Blazers",
    price: 95,
    stock: 40,
    status: "Pending",
    description:
      "Structured single-button blazer ideal for office and formal events.",
  },
  {
    _id: "PRD-30009",
    name: "Denim Shorts",
    sellerName: "Sara Khan",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana_na_folha_%28cropped%29.jpg/240px-Banana_na_folha_%28cropped%29.jpg",
    category: "Shorts",
    price: 22,
    stock: 150,
    status: "Pending",
    description:
      "Classic denim shorts with frayed hem and five-pocket styling.",
  },
  {
    _id: "PRD-30010",
    name: "Silk Blouse",
    sellerName: "Priya Sharma",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana_na_folha_%28cropped%29.jpg/240px-Banana_na_folha_%28cropped%29.jpg",
    category: "Tops",
    price: 60,
    stock: 70,
    status: "Pending",
    description:
      "Elegant silk blouse with V-neckline and pearl button closure.",
  },
];
