export const tagTypes = {
  users: "User",
  categories: "Categories",
  status: "Status",
  products: "Products",
  messages: "Message",
  templates: "Templates",
  payments: "Payments",
  news: "News",
  orders: "Order",
  chat: "Chat",
  dashboard: "Dashboard",
  policy: "policy",
  terms: "terms",
};

export const tagTypesList = [
  tagTypes.users,
  tagTypes.categories,
  tagTypes.status,
  tagTypes.products,
  tagTypes.messages,
  tagTypes.templates,
  tagTypes.news,
  tagTypes.orders,
  tagTypes.chat,
  tagTypes.dashboard,
  tagTypes.policy,
  tagTypes.terms,
];
