export const tagTypes = {
  users: "User",
  categories: "Categories",
  status: "Status",
  products: "Products",
  messages: "Message",
  templates: "Templates",
  payments: "Payments",
  news: "News",
  orders: "Order",
  chat: "Chat",
  dashboard: "Dashboard",
  policy: "policy",
  terms: "terms",
  subscriptions: "Subscriptions",
  articles: "Articles",
  analytics: "Analytics",
  aiConfig: "AiConfig",
  notification: "Notification",
  notificationHistory: "NotificationHistory",
  nutrition: "Nutrition",
  food: "Food",
  recipe: "Recipe",
};

export const tagTypesList = [
  tagTypes.users,
  tagTypes.categories,
  tagTypes.status,
  tagTypes.products,
  tagTypes.messages,
  tagTypes.templates,
  tagTypes.payments,
  tagTypes.news,
  tagTypes.orders,
  tagTypes.chat,
  tagTypes.dashboard,
  tagTypes.policy,
  tagTypes.terms,
  tagTypes.subscriptions,
  tagTypes.articles,
  tagTypes.analytics,
  tagTypes.aiConfig,
  tagTypes.notification,
  tagTypes.notificationHistory,
  tagTypes.nutrition,
  tagTypes.food,
  tagTypes.recipe,
];
